# rules for this example

all: 6 6/mk
clean:					; rm -rf 6 *.6 
test:
  set -x
  rm -f *.6 
  6/dag -d <mkfile -g
  6/mk -n
  6/mk -f - <mkfile -x

6:					; mkdir 6
6/mk: main.6				; 6l -o 6/mk -L . main.6

main.6: main.go dag.6 			; 6g -I . main.go

